name: CI

on:
  push:
    branches: "*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      run: make pack

    - uses: actions/upload-artifact@v2
      with:
        path: ./alfred-search-rubygems.alfredworkflow
